version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - ecommerce-net
  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb+srv://<your_username>:<your_password>@<your_cluster_name>.mongodb.net/<your_database_name>?retryWrites=true&w=majority
      - MONGO_ATLAS_USER=<your_username>
      - MONGO_ATLAS_PASSWORD=<your_password>
      - JWT_SECRET=your_secret_key
      - STRIPE_SECRET_KEY=sk_test_YOUR_STRIPE_SECRET_KEY
      - FRONTEND_URL=http://frontend:3000
      - REDIS_URL=redis://redis:6379
      - REDIS_PASSWORD=password
      - KAFKA_BROKERS=kafka:9092
    networks:
      - ecommerce-net
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - ecommerce-net
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - ecommerce-net
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - ecommerce-net
  test-frontend:
    build: ./frontend
    command: pnpm run test:e2e
    depends_on:
      - backend
    networks:
      - ecommerce-net
  test-backend:
    build: ./backend
    command: pnpm run test:unit:ci
    networks:
      - ecommerce-net
networks:
  ecommerce-net:
    driver: bridge
