services:
  - name: ecommerce-db
    version: 14.5
    region: nyc1
    resources:
      - cpu: 1
        memory: 1024
    backup:
      enabled: true
      schedule: "daily"
  - name: ecommerce-kafka
    version: 2.8.1
    region: nyc1
    resources:
      - cpu: 1
        memory: 2048
    backup:
      enabled: false